### ISSUE TITLE
pbasemap mosaic download message if no permission

### ISSUE THREAD

**Issue by pjhav** [samapriya/Planet-Mosaic-Quads-Download-CLI#1]
Hi Sam, thanks for addressing it in the 'mosaic_list' command. I think this information would still be important in the 'download' command as well as now when I try, it still just returns 'download'

command:
pbasemap download --geometry "C:\shapefiles\Test.geojson" --local "C:\Quads" --name "global_quarterly_2018q3_mosaic" --coverage 70

returns:
'download'

**Comment by samapriya** [comment]
Hi @pjhav 
So the idea is to use a CSV file with the mosaics list you have permission to or a mosaic name that is listed when you search for all mosaics that you have permission to. Since the assumption is that you won't have a name for a mosaic without running mosaic_list, I would not expect someone to try to download something to which they do not have permission. I will implement a better error message in the future, but nothing for now.
